<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>CNativeAPI</RootNamespace>
    <AssemblyName>CNativeAPI</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="cxx_impl/**;native/**" />
    <None Remove="cxx_impl/**;native/**" />
  </ItemGroup>

</Project>
