// Relative import to be able to reuse the C sources.
// Swift Package Manager compatible includes

// Import Cocoa framework
#import <Cocoa/Cocoa.h>

// Include source files
#include "../../../../cxx_impl/src/capi/accessibility_manager_c.cpp"
#include "../../../../cxx_impl/src/capi/application_c.cpp"
#include "../../../../cxx_impl/src/capi/autostart_c.cpp"
#include "../../../../cxx_impl/src/capi/color_c.cpp"
#include "../../../../cxx_impl/src/capi/display_c.cpp"
#include "../../../../cxx_impl/src/capi/display_manager_c.cpp"
#include "../../../../cxx_impl/src/capi/image_c.cpp"
#include "../../../../cxx_impl/src/capi/keyboard_monitor_c.cpp"
#include "../../../../cxx_impl/src/capi/menu_c.cpp"
#include "../../../../cxx_impl/src/capi/message_dialog_c.cpp"
#include "../../../../cxx_impl/src/capi/positioning_strategy_c.cpp"
#include "../../../../cxx_impl/src/capi/preferences_c.cpp"
#include "../../../../cxx_impl/src/capi/secure_storage_c.cpp"
#include "../../../../cxx_impl/src/capi/shortcut_c.cpp"
#include "../../../../cxx_impl/src/capi/shortcut_manager_c.cpp"
#include "../../../../cxx_impl/src/capi/string_utils_c.cpp"
#include "../../../../cxx_impl/src/capi/tray_icon_c.cpp"
#include "../../../../cxx_impl/src/capi/tray_manager_c.cpp"
#include "../../../../cxx_impl/src/capi/window_c.cpp"
#include "../../../../cxx_impl/src/capi/window_manager_c.cpp"
#include "../../../../cxx_impl/src/platform/macos/accessibility_manager_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/application_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/autostart_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/display_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/display_manager_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/image_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/keyboard_monitor_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/menu_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/message_dialog_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/preferences_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/secure_storage_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/tray_icon_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/tray_manager_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/window_macos.mm"
#include "../../../../cxx_impl/src/platform/macos/window_manager_macos.mm"
#include "../../../../cxx_impl/src/foundation/color.cpp"
#include "../../../../cxx_impl/src/foundation/id_allocator.cpp"
#include "../../../../cxx_impl/src/foundation/keyboard.cpp"
#include "../../../../cxx_impl/src/accessibility_manager.cpp"
#include "../../../../cxx_impl/src/application.cpp"
#include "../../../../cxx_impl/src/dialog.cpp"
#include "../../../../cxx_impl/src/display_manager.cpp"
#include "../../../../cxx_impl/src/menu.cpp"
#include "../../../../cxx_impl/src/positioning_strategy.cpp"
#include "../../../../cxx_impl/src/preferences.cpp"
#include "../../../../cxx_impl/src/secure_storage.cpp"
#include "../../../../cxx_impl/src/shortcut.cpp"
#include "../../../../cxx_impl/src/shortcut_manager.cpp"
#include "../../../../cxx_impl/src/tray_manager.cpp"
#include "../../../../cxx_impl/src/window_manager.cpp"
#include "../../../../cxx_impl/src/window_registry.cpp"
