// Relative import to be able to reuse the C sources.
// See the comment in ../nativeapi.podspec for more information.

// Include source files
#include "../../src/libnativeapi/src/capi/accessibility_manager_c.cpp"
#include "../../src/libnativeapi/src/capi/application_c.cpp"
#include "../../src/libnativeapi/src/capi/display_c.cpp"
#include "../../src/libnativeapi/src/capi/display_manager_c.cpp"
#include "../../src/libnativeapi/src/capi/image_c.cpp"
#include "../../src/libnativeapi/src/capi/keyboard_monitor_c.cpp"
#include "../../src/libnativeapi/src/capi/menu_c.cpp"
#include "../../src/libnativeapi/src/capi/positioning_strategy_c.cpp"
#include "../../src/libnativeapi/src/capi/run_example_app_c.cpp"
#include "../../src/libnativeapi/src/capi/string_utils_c.cpp"
#include "../../src/libnativeapi/src/capi/tray_icon_c.cpp"
#include "../../src/libnativeapi/src/capi/tray_manager_c.cpp"
#include "../../src/libnativeapi/src/capi/window_c.cpp"
#include "../../src/libnativeapi/src/capi/window_manager_c.cpp"
#include "../../src/libnativeapi/src/accessibility_manager.cpp"
#include "../../src/libnativeapi/src/application.cpp"
#include "../../src/libnativeapi/src/display_manager.cpp"
#include "../../src/libnativeapi/src/foundation/id_allocator.cpp"
#include "../../src/libnativeapi/src/foundation/positioning_strategy.cpp"
#include "../../src/libnativeapi/src/menu.cpp"
#include "../../src/libnativeapi/src/platform/ios/accessibility_manager_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/application_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/display_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/display_manager_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/image_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/keyboard_monitor_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/menu_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/tray_icon_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/tray_manager_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/window_ios.mm"
#include "../../src/libnativeapi/src/platform/ios/window_manager_ios.mm"
#include "../../src/libnativeapi/src/tray_manager.cpp"
#include "../../src/libnativeapi/src/window_manager.cpp"
