/* automatically generated by rust-bindgen 0.72.1 */

pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __WORDSIZE: u32 = 64;
pub const __has_safe_buffers: u32 = 1;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_ONLY_VERS_1050: u32 = 1;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_EXTSN: &[u8; 14] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
pub const __STDC_WANT_LIB_EXT1__: u32 = 1;
pub const __DARWIN_NO_LONG_LONG: u32 = 0;
pub const _DARWIN_FEATURE_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_VERS_1050: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: u32 = 3;
pub const __has_ptrcheck: u32 = 0;
pub const __has_bounds_safety_attributes: u32 = 0;
pub const USE_CLANG_TYPES: u32 = 0;
pub const __PTHREAD_SIZE__: u32 = 8176;
pub const __PTHREAD_ATTR_SIZE__: u32 = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: u32 = 8;
pub const __PTHREAD_MUTEX_SIZE__: u32 = 56;
pub const __PTHREAD_CONDATTR_SIZE__: u32 = 8;
pub const __PTHREAD_COND_SIZE__: u32 = 40;
pub const __PTHREAD_ONCE_SIZE__: u32 = 8;
pub const __PTHREAD_RWLOCK_SIZE__: u32 = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: u32 = 16;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -32768;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 32767;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 65535;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const UINTPTR_MAX: i32 = -1;
pub const SIZE_MAX: i32 = -1;
pub const RSIZE_MAX: i32 = -1;
pub const WINT_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
unsafe extern "C" {
    #[doc = " @brief Enables system accessibility features\n\n This function activates accessibility functionality across the system.\n The operation is idempotent - calling it multiple times has the same\n effect as calling it once.\n\n @note This operation may require system permissions depending on the\n       platform implementation."]
    pub fn native_accessibility_manager_enable();
}
unsafe extern "C" {
    #[doc = " @brief Checks if accessibility features are currently enabled\n\n @return true if accessibility is enabled, false otherwise\n\n This function provides a quick way to query the current state of\n accessibility features without modifying the system state."]
    pub fn native_accessibility_manager_is_enabled() -> bool;
}
pub type wchar_t = ::std::os::raw::c_int;
pub type max_align_t = f64;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: ::std::os::raw::c_longlong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t"][::std::mem::size_of::<__mbstate_t>() - 128usize];
    ["Alignment of __mbstate_t"][::std::mem::align_of::<__mbstate_t>() - 8usize];
    ["Offset of field: __mbstate_t::__mbstate8"]
        [::std::mem::offset_of!(__mbstate_t, __mbstate8) - 0usize];
    ["Offset of field: __mbstate_t::_mbstateL"]
        [::std::mem::offset_of!(__mbstate_t, _mbstateL) - 0usize];
};
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __darwin_pthread_handler_rec"]
        [::std::mem::size_of::<__darwin_pthread_handler_rec>() - 24usize];
    ["Alignment of __darwin_pthread_handler_rec"]
        [::std::mem::align_of::<__darwin_pthread_handler_rec>() - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__routine"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __routine) - 0usize];
    ["Offset of field: __darwin_pthread_handler_rec::__arg"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __arg) - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__next"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_attr_t"][::std::mem::size_of::<_opaque_pthread_attr_t>() - 64usize];
    ["Alignment of _opaque_pthread_attr_t"]
        [::std::mem::align_of::<_opaque_pthread_attr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_attr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_attr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_cond_t"][::std::mem::size_of::<_opaque_pthread_cond_t>() - 48usize];
    ["Alignment of _opaque_pthread_cond_t"]
        [::std::mem::align_of::<_opaque_pthread_cond_t>() - 8usize];
    ["Offset of field: _opaque_pthread_cond_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_cond_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_condattr_t"]
        [::std::mem::size_of::<_opaque_pthread_condattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_condattr_t"]
        [::std::mem::align_of::<_opaque_pthread_condattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_condattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_condattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutex_t"][::std::mem::size_of::<_opaque_pthread_mutex_t>() - 64usize];
    ["Alignment of _opaque_pthread_mutex_t"]
        [::std::mem::align_of::<_opaque_pthread_mutex_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutex_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutex_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutexattr_t"]
        [::std::mem::size_of::<_opaque_pthread_mutexattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_mutexattr_t"]
        [::std::mem::align_of::<_opaque_pthread_mutexattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_once_t"][::std::mem::size_of::<_opaque_pthread_once_t>() - 16usize];
    ["Alignment of _opaque_pthread_once_t"]
        [::std::mem::align_of::<_opaque_pthread_once_t>() - 8usize];
    ["Offset of field: _opaque_pthread_once_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_once_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlock_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlock_t>() - 200usize];
    ["Alignment of _opaque_pthread_rwlock_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlock_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlockattr_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlockattr_t>() - 24usize];
    ["Alignment of _opaque_pthread_rwlockattr_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlockattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_t"][::std::mem::size_of::<_opaque_pthread_t>() - 8192usize];
    ["Alignment of _opaque_pthread_t"][::std::mem::align_of::<_opaque_pthread_t>() - 8usize];
    ["Offset of field: _opaque_pthread_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_t::__cleanup_stack"]
        [::std::mem::offset_of!(_opaque_pthread_t, __cleanup_stack) - 8usize];
    ["Offset of field: _opaque_pthread_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_t, __opaque) - 16usize];
};
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
#[doc = " Representation of a point"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_point_t {
    pub x: f64,
    pub y: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_point_t"][::std::mem::size_of::<native_point_t>() - 16usize];
    ["Alignment of native_point_t"][::std::mem::align_of::<native_point_t>() - 8usize];
    ["Offset of field: native_point_t::x"][::std::mem::offset_of!(native_point_t, x) - 0usize];
    ["Offset of field: native_point_t::y"][::std::mem::offset_of!(native_point_t, y) - 8usize];
};
#[doc = " Representation of a point"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_size_t {
    pub width: f64,
    pub height: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_size_t"][::std::mem::size_of::<native_size_t>() - 16usize];
    ["Alignment of native_size_t"][::std::mem::align_of::<native_size_t>() - 8usize];
    ["Offset of field: native_size_t::width"]
        [::std::mem::offset_of!(native_size_t, width) - 0usize];
    ["Offset of field: native_size_t::height"]
        [::std::mem::offset_of!(native_size_t, height) - 8usize];
};
#[doc = " Representation of a rectangle"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_rectangle_t {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_rectangle_t"][::std::mem::size_of::<native_rectangle_t>() - 32usize];
    ["Alignment of native_rectangle_t"][::std::mem::align_of::<native_rectangle_t>() - 8usize];
    ["Offset of field: native_rectangle_t::x"]
        [::std::mem::offset_of!(native_rectangle_t, x) - 0usize];
    ["Offset of field: native_rectangle_t::y"]
        [::std::mem::offset_of!(native_rectangle_t, y) - 8usize];
    ["Offset of field: native_rectangle_t::width"]
        [::std::mem::offset_of!(native_rectangle_t, width) - 16usize];
    ["Offset of field: native_rectangle_t::height"]
        [::std::mem::offset_of!(native_rectangle_t, height) - 24usize];
};
#[doc = " Position above the anchor, horizontally centered."]
pub const native_placement_t_NATIVE_PLACEMENT_TOP: native_placement_t = 0;
#[doc = " Position above the anchor, aligned to the start (left)."]
pub const native_placement_t_NATIVE_PLACEMENT_TOP_START: native_placement_t = 1;
#[doc = " Position above the anchor, aligned to the end (right)."]
pub const native_placement_t_NATIVE_PLACEMENT_TOP_END: native_placement_t = 2;
#[doc = " Position to the right of the anchor, vertically centered."]
pub const native_placement_t_NATIVE_PLACEMENT_RIGHT: native_placement_t = 3;
#[doc = " Position to the right of the anchor, aligned to the start (top)."]
pub const native_placement_t_NATIVE_PLACEMENT_RIGHT_START: native_placement_t = 4;
#[doc = " Position to the right of the anchor, aligned to the end (bottom)."]
pub const native_placement_t_NATIVE_PLACEMENT_RIGHT_END: native_placement_t = 5;
#[doc = " Position below the anchor, horizontally centered."]
pub const native_placement_t_NATIVE_PLACEMENT_BOTTOM: native_placement_t = 6;
#[doc = " Position below the anchor, aligned to the start (left)."]
pub const native_placement_t_NATIVE_PLACEMENT_BOTTOM_START: native_placement_t = 7;
#[doc = " Position below the anchor, aligned to the end (right)."]
pub const native_placement_t_NATIVE_PLACEMENT_BOTTOM_END: native_placement_t = 8;
#[doc = " Position to the left of the anchor, vertically centered."]
pub const native_placement_t_NATIVE_PLACEMENT_LEFT: native_placement_t = 9;
#[doc = " Position to the left of the anchor, aligned to the start (top)."]
pub const native_placement_t_NATIVE_PLACEMENT_LEFT_START: native_placement_t = 10;
#[doc = " Position to the left of the anchor, aligned to the end (bottom)."]
pub const native_placement_t_NATIVE_PLACEMENT_LEFT_END: native_placement_t = 11;
#[doc = " Placement options for positioning UI elements relative to an anchor."]
pub type native_placement_t = ::std::os::raw::c_uint;
#[doc = " Window ID type"]
pub type native_window_id_t = ::std::os::raw::c_long;
#[doc = " Window options structure for creating windows"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_window_options_t {
    pub title: *mut ::std::os::raw::c_char,
    pub size: native_size_t,
    pub minimum_size: native_size_t,
    pub maximum_size: native_size_t,
    pub centered: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_window_options_t"][::std::mem::size_of::<native_window_options_t>() - 64usize];
    ["Alignment of native_window_options_t"]
        [::std::mem::align_of::<native_window_options_t>() - 8usize];
    ["Offset of field: native_window_options_t::title"]
        [::std::mem::offset_of!(native_window_options_t, title) - 0usize];
    ["Offset of field: native_window_options_t::size"]
        [::std::mem::offset_of!(native_window_options_t, size) - 8usize];
    ["Offset of field: native_window_options_t::minimum_size"]
        [::std::mem::offset_of!(native_window_options_t, minimum_size) - 24usize];
    ["Offset of field: native_window_options_t::maximum_size"]
        [::std::mem::offset_of!(native_window_options_t, maximum_size) - 40usize];
    ["Offset of field: native_window_options_t::centered"]
        [::std::mem::offset_of!(native_window_options_t, centered) - 56usize];
};
#[doc = " Opaque window handle"]
pub type native_window_t = *mut ::std::os::raw::c_void;
#[doc = " Window list structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_window_list_t {
    pub windows: *mut native_window_t,
    pub count: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_window_list_t"][::std::mem::size_of::<native_window_list_t>() - 16usize];
    ["Alignment of native_window_list_t"][::std::mem::align_of::<native_window_list_t>() - 8usize];
    ["Offset of field: native_window_list_t::windows"]
        [::std::mem::offset_of!(native_window_list_t, windows) - 0usize];
    ["Offset of field: native_window_list_t::count"]
        [::std::mem::offset_of!(native_window_list_t, count) - 8usize];
};
unsafe extern "C" {
    pub fn native_window_options_create() -> *mut native_window_options_t;
}
unsafe extern "C" {
    pub fn native_window_options_destroy(options: *mut native_window_options_t);
}
unsafe extern "C" {
    pub fn native_window_options_set_title(
        options: *mut native_window_options_t,
        title: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn native_window_options_set_size(
        options: *mut native_window_options_t,
        width: f64,
        height: f64,
    );
}
unsafe extern "C" {
    pub fn native_window_options_set_minimum_size(
        options: *mut native_window_options_t,
        width: f64,
        height: f64,
    );
}
unsafe extern "C" {
    pub fn native_window_options_set_maximum_size(
        options: *mut native_window_options_t,
        width: f64,
        height: f64,
    );
}
unsafe extern "C" {
    pub fn native_window_options_set_centered(
        options: *mut native_window_options_t,
        centered: bool,
    );
}
unsafe extern "C" {
    pub fn native_window_get_id(window: native_window_t) -> native_window_id_t;
}
unsafe extern "C" {
    pub fn native_window_focus(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_blur(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_is_focused(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_show(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_show_inactive(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_hide(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_is_visible(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_maximize(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_unmaximize(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_is_maximized(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_minimize(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_restore(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_is_minimized(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_fullscreen(window: native_window_t, is_fullscreen: bool);
}
unsafe extern "C" {
    pub fn native_window_is_fullscreen(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_bounds(window: native_window_t, bounds: native_rectangle_t);
}
unsafe extern "C" {
    pub fn native_window_get_bounds(window: native_window_t) -> native_rectangle_t;
}
unsafe extern "C" {
    pub fn native_window_set_size(window: native_window_t, width: f64, height: f64, animate: bool);
}
unsafe extern "C" {
    pub fn native_window_get_size(window: native_window_t) -> native_size_t;
}
unsafe extern "C" {
    pub fn native_window_set_content_size(window: native_window_t, width: f64, height: f64);
}
unsafe extern "C" {
    pub fn native_window_get_content_size(window: native_window_t) -> native_size_t;
}
unsafe extern "C" {
    pub fn native_window_set_content_bounds(window: native_window_t, bounds: native_rectangle_t);
}
unsafe extern "C" {
    pub fn native_window_get_content_bounds(window: native_window_t) -> native_rectangle_t;
}
unsafe extern "C" {
    pub fn native_window_set_minimum_size(window: native_window_t, width: f64, height: f64);
}
unsafe extern "C" {
    pub fn native_window_get_minimum_size(window: native_window_t) -> native_size_t;
}
unsafe extern "C" {
    pub fn native_window_set_maximum_size(window: native_window_t, width: f64, height: f64);
}
unsafe extern "C" {
    pub fn native_window_get_maximum_size(window: native_window_t) -> native_size_t;
}
unsafe extern "C" {
    pub fn native_window_set_position(window: native_window_t, x: f64, y: f64);
}
unsafe extern "C" {
    pub fn native_window_get_position(window: native_window_t) -> native_point_t;
}
unsafe extern "C" {
    pub fn native_window_set_resizable(window: native_window_t, resizable: bool);
}
unsafe extern "C" {
    pub fn native_window_is_resizable(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_movable(window: native_window_t, movable: bool);
}
unsafe extern "C" {
    pub fn native_window_is_movable(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_minimizable(window: native_window_t, minimizable: bool);
}
unsafe extern "C" {
    pub fn native_window_is_minimizable(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_maximizable(window: native_window_t, maximizable: bool);
}
unsafe extern "C" {
    pub fn native_window_is_maximizable(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_fullscreenable(window: native_window_t, fullscreenable: bool);
}
unsafe extern "C" {
    pub fn native_window_is_fullscreenable(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_closable(window: native_window_t, closable: bool);
}
unsafe extern "C" {
    pub fn native_window_is_closable(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_always_on_top(window: native_window_t, always_on_top: bool);
}
unsafe extern "C" {
    pub fn native_window_is_always_on_top(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_title(
        window: native_window_t,
        title: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn native_window_get_title(window: native_window_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn native_window_set_has_shadow(window: native_window_t, has_shadow: bool);
}
unsafe extern "C" {
    pub fn native_window_has_shadow(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_opacity(window: native_window_t, opacity: f32);
}
unsafe extern "C" {
    pub fn native_window_get_opacity(window: native_window_t) -> f32;
}
unsafe extern "C" {
    pub fn native_window_set_visible_on_all_workspaces(window: native_window_t, visible: bool);
}
unsafe extern "C" {
    pub fn native_window_is_visible_on_all_workspaces(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_ignore_mouse_events(window: native_window_t, ignore: bool);
}
unsafe extern "C" {
    pub fn native_window_is_ignore_mouse_events(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_set_focusable(window: native_window_t, focusable: bool);
}
unsafe extern "C" {
    pub fn native_window_is_focusable(window: native_window_t) -> bool;
}
unsafe extern "C" {
    pub fn native_window_start_dragging(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_start_resizing(window: native_window_t);
}
unsafe extern "C" {
    pub fn native_window_get_native_object(window: native_window_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn native_window_free_string(str_: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn native_window_list_free(list: *mut native_window_list_t);
}
#[doc = " @brief Opaque handle for the Application instance"]
pub type native_application_t = *mut ::std::os::raw::c_void;
pub const native_application_event_type_t_NATIVE_APPLICATION_EVENT_STARTED:
    native_application_event_type_t = 0;
pub const native_application_event_type_t_NATIVE_APPLICATION_EVENT_EXITING:
    native_application_event_type_t = 1;
pub const native_application_event_type_t_NATIVE_APPLICATION_EVENT_ACTIVATED:
    native_application_event_type_t = 2;
pub const native_application_event_type_t_NATIVE_APPLICATION_EVENT_DEACTIVATED:
    native_application_event_type_t = 3;
pub const native_application_event_type_t_NATIVE_APPLICATION_EVENT_QUIT_REQUESTED:
    native_application_event_type_t = 4;
#[doc = " @brief Application event types"]
pub type native_application_event_type_t = ::std::os::raw::c_uint;
#[doc = " @brief Application event structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_application_event_t {
    pub type_: native_application_event_type_t,
    pub exit_code: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_application_event_t"]
        [::std::mem::size_of::<native_application_event_t>() - 8usize];
    ["Alignment of native_application_event_t"]
        [::std::mem::align_of::<native_application_event_t>() - 4usize];
    ["Offset of field: native_application_event_t::type_"]
        [::std::mem::offset_of!(native_application_event_t, type_) - 0usize];
    ["Offset of field: native_application_event_t::exit_code"]
        [::std::mem::offset_of!(native_application_event_t, exit_code) - 4usize];
};
#[doc = " @brief Application event callback function type"]
pub type native_application_event_callback_t =
    ::std::option::Option<unsafe extern "C" fn(event: *const native_application_event_t)>;
unsafe extern "C" {
    #[doc = " @brief Get the singleton instance of Application\n\n @return Handle to the singleton Application instance"]
    pub fn native_application_get_instance() -> native_application_t;
}
unsafe extern "C" {
    #[doc = " @brief Run the application main event loop\n\n @param app Application handle (must not be NULL)\n @return Exit code of the application (0 for success)"]
    pub fn native_application_run(app: native_application_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Run the application with the specified window\n\n @param app Application handle (must not be NULL)\n @param window Window handle (must not be NULL)\n @return Exit code of the application (0 for success)"]
    pub fn native_application_run_with_window(
        app: native_application_t,
        window: native_window_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Request the application to quit\n\n @param app Application handle (must not be NULL)\n @param exit_code The exit code to use when quitting (default: 0)"]
    pub fn native_application_quit(app: native_application_t, exit_code: ::std::os::raw::c_int);
}
unsafe extern "C" {
    #[doc = " @brief Check if the application is currently running\n\n @param app Application handle (must not be NULL)\n @return true if the application is running, false otherwise"]
    pub fn native_application_is_running(app: native_application_t) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Check if this is a single instance application\n\n @param app Application handle (must not be NULL)\n @return true if only one instance is allowed, false otherwise"]
    pub fn native_application_is_single_instance(app: native_application_t) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Set the application icon\n\n @param app Application handle (must not be NULL)\n @param icon_path Path to the icon file (must not be NULL)\n @return true if the icon was set successfully, false otherwise"]
    pub fn native_application_set_icon(
        app: native_application_t,
        icon_path: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Show or hide the dock icon (macOS only)\n\n @param app Application handle (must not be NULL)\n @param visible true to show the dock icon, false to hide it\n @return true if the operation succeeded, false otherwise"]
    pub fn native_application_set_dock_icon_visible(
        app: native_application_t,
        visible: bool,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Add an event listener for application events\n\n @param app Application handle (must not be NULL)\n @param callback Event callback function (must not be NULL)\n @return Listener ID that can be used to remove the listener, or 0 on failure"]
    pub fn native_application_add_event_listener(
        app: native_application_t,
        callback: native_application_event_callback_t,
    ) -> usize;
}
unsafe extern "C" {
    #[doc = " @brief Remove an event listener by ID\n\n @param app Application handle (must not be NULL)\n @param listener_id The ID returned by native_application_add_event_listener\n @return true if the listener was found and removed, false otherwise"]
    pub fn native_application_remove_event_listener(
        app: native_application_t,
        listener_id: usize,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Convenience function to run the application with the specified window\n\n This is equivalent to calling native_application_run_with_window with the singleton instance.\n This function provides a simple way to run an application without explicitly\n accessing the singleton.\n\n @param window Window handle (must not be NULL)\n @return Exit code of the application (0 for success)"]
    pub fn native_run_app(window: native_window_t) -> ::std::os::raw::c_int;
}
pub const native_display_orientation_t_NATIVE_DISPLAY_ORIENTATION_PORTRAIT:
    native_display_orientation_t = 0;
pub const native_display_orientation_t_NATIVE_DISPLAY_ORIENTATION_LANDSCAPE:
    native_display_orientation_t = 90;
pub const native_display_orientation_t_NATIVE_DISPLAY_ORIENTATION_PORTRAIT_FLIPPED:
    native_display_orientation_t = 180;
pub const native_display_orientation_t_NATIVE_DISPLAY_ORIENTATION_LANDSCAPE_FLIPPED:
    native_display_orientation_t = 270;
#[doc = " Display orientation enumeration"]
pub type native_display_orientation_t = ::std::os::raw::c_uint;
#[doc = " Opaque display handle\n Align with window handle design: use a raw pointer to underlying C++ type"]
pub type native_display_t = *mut ::std::os::raw::c_void;
#[doc = " Display list structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_display_list_t {
    pub displays: *mut native_display_t,
    pub count: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_display_list_t"][::std::mem::size_of::<native_display_list_t>() - 16usize];
    ["Alignment of native_display_list_t"]
        [::std::mem::align_of::<native_display_list_t>() - 8usize];
    ["Offset of field: native_display_list_t::displays"]
        [::std::mem::offset_of!(native_display_list_t, displays) - 0usize];
    ["Offset of field: native_display_list_t::count"]
        [::std::mem::offset_of!(native_display_list_t, count) - 8usize];
};
unsafe extern "C" {
    pub fn native_display_get_id(display: native_display_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn native_display_get_name(display: native_display_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn native_display_get_position(display: native_display_t) -> native_point_t;
}
unsafe extern "C" {
    pub fn native_display_get_size(display: native_display_t) -> native_size_t;
}
unsafe extern "C" {
    pub fn native_display_get_work_area(display: native_display_t) -> native_rectangle_t;
}
unsafe extern "C" {
    pub fn native_display_get_scale_factor(display: native_display_t) -> f64;
}
unsafe extern "C" {
    pub fn native_display_is_primary(display: native_display_t) -> bool;
}
unsafe extern "C" {
    pub fn native_display_get_orientation(
        display: native_display_t,
    ) -> native_display_orientation_t;
}
unsafe extern "C" {
    pub fn native_display_get_refresh_rate(display: native_display_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn native_display_get_bit_depth(display: native_display_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn native_display_get_native_object(
        display: native_display_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn native_display_free(display: native_display_t);
}
unsafe extern "C" {
    pub fn native_display_list_free(list: *mut native_display_list_t);
}
unsafe extern "C" {
    pub fn native_display_manager_get_all() -> native_display_list_t;
}
unsafe extern "C" {
    pub fn native_display_manager_get_primary() -> native_display_t;
}
unsafe extern "C" {
    pub fn native_display_manager_get_cursor_position() -> native_point_t;
}
pub type rsize_t = ::std::os::raw::c_ulong;
#[doc = " Opaque handle for image objects"]
pub type native_image_t = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    #[doc = " Create an image from a file path\n @param file_path Path to the image file\n @return Image handle, or NULL if loading failed"]
    pub fn native_image_from_file(file_path: *const ::std::os::raw::c_char) -> native_image_t;
}
unsafe extern "C" {
    #[doc = " Create an image from base64-encoded data\n @param base64_data Base64-encoded image data, with or without data URI prefix\n @return Image handle, or NULL if decoding failed"]
    pub fn native_image_from_base64(base64_data: *const ::std::os::raw::c_char) -> native_image_t;
}
unsafe extern "C" {
    #[doc = " Destroy an image and release its resources\n @param image The image to destroy"]
    pub fn native_image_destroy(image: native_image_t);
}
unsafe extern "C" {
    #[doc = " Get the size of an image in pixels\n @param image The image\n @return Size of the image (width and height will be 0 if invalid)"]
    pub fn native_image_get_size(image: native_image_t) -> native_size_t;
}
unsafe extern "C" {
    #[doc = " Get the image format string for debugging purposes\n @param image The image\n @return The image format (e.g., \"PNG\", \"JPEG\", \"GIF\"), or NULL if unknown\n (caller must free)"]
    pub fn native_image_get_format(image: native_image_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Convert an image to base64-encoded PNG data\n @param image The image\n @return Base64-encoded PNG data with data URI prefix (caller must free), or\n NULL on error"]
    pub fn native_image_to_base64(image: native_image_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Save an image to a file\n @param image The image\n @param file_path Path where the image should be saved\n @return true if saved successfully, false otherwise"]
    pub fn native_image_save_to_file(
        image: native_image_t,
        file_path: *const ::std::os::raw::c_char,
    ) -> bool;
}
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_NONE: native_modifier_key_t = 0;
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_SHIFT: native_modifier_key_t = 1;
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_CTRL: native_modifier_key_t = 2;
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_ALT: native_modifier_key_t = 4;
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_META: native_modifier_key_t = 8;
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_FN: native_modifier_key_t = 16;
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_CAPS_LOCK: native_modifier_key_t = 32;
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_NUM_LOCK: native_modifier_key_t = 64;
pub const native_modifier_key_t_NATIVE_MODIFIER_KEY_SCROLL_LOCK: native_modifier_key_t = 128;
#[doc = " Modifier key enumeration for C API"]
pub type native_modifier_key_t = ::std::os::raw::c_uint;
#[doc = " Callback function type for key pressed events\n @param keycode The key code that was pressed\n @param user_data User-provided data passed to the callback"]
pub type native_key_pressed_callback_t = ::std::option::Option<
    unsafe extern "C" fn(keycode: ::std::os::raw::c_int, user_data: *mut ::std::os::raw::c_void),
>;
#[doc = " Callback function type for key released events\n @param keycode The key code that was released\n @param user_data User-provided data passed to the callback"]
pub type native_key_released_callback_t = ::std::option::Option<
    unsafe extern "C" fn(keycode: ::std::os::raw::c_int, user_data: *mut ::std::os::raw::c_void),
>;
#[doc = " Callback function type for modifier keys changed events\n @param modifier_keys Bitwise OR of active modifier keys\n @param user_data User-provided data passed to the callback"]
pub type native_modifier_keys_changed_callback_t = ::std::option::Option<
    unsafe extern "C" fn(modifier_keys: u32, user_data: *mut ::std::os::raw::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_keyboard_monitor_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    #[doc = " Create a new keyboard monitor instance\n @return Pointer to keyboard monitor instance, or NULL on failure"]
    pub fn native_keyboard_monitor_create() -> *mut native_keyboard_monitor_t;
}
unsafe extern "C" {
    #[doc = " Destroy a keyboard monitor instance\n @param monitor Pointer to keyboard monitor instance to destroy"]
    pub fn native_keyboard_monitor_destroy(monitor: *mut native_keyboard_monitor_t);
}
unsafe extern "C" {
    #[doc = " Set callback functions for keyboard events\n @param monitor Pointer to keyboard monitor instance\n @param on_key_pressed Callback for key pressed events (can be NULL)\n @param on_key_released Callback for key released events (can be NULL)\n @param on_modifier_keys_changed Callback for modifier keys changed events\n (can be NULL)\n @param user_data User data to pass to callbacks\n @return true on success, false on failure"]
    pub fn native_keyboard_monitor_set_callbacks(
        monitor: *mut native_keyboard_monitor_t,
        on_key_pressed: native_key_pressed_callback_t,
        on_key_released: native_key_released_callback_t,
        on_modifier_keys_changed: native_modifier_keys_changed_callback_t,
        user_data: *mut ::std::os::raw::c_void,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Start keyboard monitoring\n @param monitor Pointer to keyboard monitor instance\n @return true on success, false on failure"]
    pub fn native_keyboard_monitor_start(monitor: *mut native_keyboard_monitor_t) -> bool;
}
unsafe extern "C" {
    #[doc = " Stop keyboard monitoring\n @param monitor Pointer to keyboard monitor instance\n @return true on success, false on failure"]
    pub fn native_keyboard_monitor_stop(monitor: *mut native_keyboard_monitor_t) -> bool;
}
unsafe extern "C" {
    #[doc = " Check if keyboard monitoring is active\n @param monitor Pointer to keyboard monitor instance\n @return true if monitoring is active, false otherwise"]
    pub fn native_keyboard_monitor_is_monitoring(monitor: *const native_keyboard_monitor_t)
        -> bool;
}
pub const native_positioning_strategy_type_t_NATIVE_POSITIONING_ABSOLUTE:
    native_positioning_strategy_type_t = 0;
pub const native_positioning_strategy_type_t_NATIVE_POSITIONING_CURSOR_POSITION:
    native_positioning_strategy_type_t = 1;
pub const native_positioning_strategy_type_t_NATIVE_POSITIONING_RELATIVE:
    native_positioning_strategy_type_t = 2;
#[doc = " Type of positioning strategy"]
pub type native_positioning_strategy_type_t = ::std::os::raw::c_uint;
#[doc = " Opaque handle for positioning strategy"]
pub type native_positioning_strategy_t = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    #[doc = " Create a positioning strategy for absolute positioning at fixed coordinates\n @param point Point in screen coordinates\n @return Positioning strategy handle"]
    pub fn native_positioning_strategy_absolute(
        point: *const native_point_t,
    ) -> native_positioning_strategy_t;
}
unsafe extern "C" {
    #[doc = " Create a positioning strategy for positioning at current mouse location\n @return Positioning strategy handle"]
    pub fn native_positioning_strategy_cursor_position() -> native_positioning_strategy_t;
}
unsafe extern "C" {
    #[doc = " Create a positioning strategy for positioning relative to a rectangle\n @param rect Rectangle in screen coordinates to position relative to\n @param offset Offset point to apply to the position, or NULL for no offset\n @return Positioning strategy handle\n\n @example\n ```c\n native_rectangle_t buttonRect = {100, 100, 50, 30};\n native_point_t offset = {0, 10};\n native_positioning_strategy_t strategy = native_positioning_strategy_relative(&buttonRect,\n &offset); native_menu_open(menu, strategy); native_positioning_strategy_free(strategy);\n ```"]
    pub fn native_positioning_strategy_relative(
        rect: *const native_rectangle_t,
        offset: *const native_point_t,
    ) -> native_positioning_strategy_t;
}
unsafe extern "C" {
    #[doc = " Create a positioning strategy for positioning relative to a window\n @param window Window to position relative to\n @param offset Offset point to apply to the position, or NULL for no offset\n @return Positioning strategy handle, or NULL if window is invalid\n\n This function obtains the window's bounds using native_window_get_bounds()\n and creates a Relative positioning strategy based on those bounds.\n\n @example\n ```c\n native_window_t window = native_window_manager_create(&options);\n native_point_t offset = {0, 10};\n native_positioning_strategy_t strategy = native_positioning_strategy_relative_to_window(window,\n &offset); native_menu_open(menu, strategy); native_positioning_strategy_free(strategy);\n ```"]
    pub fn native_positioning_strategy_relative_to_window(
        window: native_window_t,
        offset: *const native_point_t,
    ) -> native_positioning_strategy_t;
}
unsafe extern "C" {
    #[doc = " Free a positioning strategy handle\n @param strategy The positioning strategy to free"]
    pub fn native_positioning_strategy_free(strategy: native_positioning_strategy_t);
}
#[doc = " Opaque handles for menu objects"]
pub type native_menu_t = *mut ::std::os::raw::c_void;
pub type native_menu_item_t = *mut ::std::os::raw::c_void;
#[doc = " Menu and menu item identifiers"]
pub type native_menu_id_t = ::std::os::raw::c_long;
pub type native_menu_item_id_t = ::std::os::raw::c_long;
pub const native_menu_item_type_t_NATIVE_MENU_ITEM_TYPE_NORMAL: native_menu_item_type_t = 0;
pub const native_menu_item_type_t_NATIVE_MENU_ITEM_TYPE_CHECKBOX: native_menu_item_type_t = 1;
pub const native_menu_item_type_t_NATIVE_MENU_ITEM_TYPE_RADIO: native_menu_item_type_t = 2;
pub const native_menu_item_type_t_NATIVE_MENU_ITEM_TYPE_SEPARATOR: native_menu_item_type_t = 3;
pub const native_menu_item_type_t_NATIVE_MENU_ITEM_TYPE_SUBMENU: native_menu_item_type_t = 4;
#[doc = " Menu item types"]
pub type native_menu_item_type_t = ::std::os::raw::c_uint;
pub const native_menu_item_state_t_NATIVE_MENU_ITEM_STATE_UNCHECKED: native_menu_item_state_t = 0;
pub const native_menu_item_state_t_NATIVE_MENU_ITEM_STATE_CHECKED: native_menu_item_state_t = 1;
pub const native_menu_item_state_t_NATIVE_MENU_ITEM_STATE_MIXED: native_menu_item_state_t = 2;
#[doc = " Menu item states"]
pub type native_menu_item_state_t = ::std::os::raw::c_uint;
pub const native_accelerator_modifier_t_NATIVE_ACCELERATOR_MODIFIER_NONE:
    native_accelerator_modifier_t = 0;
pub const native_accelerator_modifier_t_NATIVE_ACCELERATOR_MODIFIER_CTRL:
    native_accelerator_modifier_t = 1;
pub const native_accelerator_modifier_t_NATIVE_ACCELERATOR_MODIFIER_ALT:
    native_accelerator_modifier_t = 2;
pub const native_accelerator_modifier_t_NATIVE_ACCELERATOR_MODIFIER_SHIFT:
    native_accelerator_modifier_t = 4;
pub const native_accelerator_modifier_t_NATIVE_ACCELERATOR_MODIFIER_META:
    native_accelerator_modifier_t = 8;
#[doc = " Keyboard accelerator modifier flags"]
pub type native_accelerator_modifier_t = ::std::os::raw::c_uint;
#[doc = " Keyboard accelerator structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_keyboard_accelerator_t {
    pub modifiers: ::std::os::raw::c_int,
    pub key: [::std::os::raw::c_char; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_keyboard_accelerator_t"]
        [::std::mem::size_of::<native_keyboard_accelerator_t>() - 68usize];
    ["Alignment of native_keyboard_accelerator_t"]
        [::std::mem::align_of::<native_keyboard_accelerator_t>() - 4usize];
    ["Offset of field: native_keyboard_accelerator_t::modifiers"]
        [::std::mem::offset_of!(native_keyboard_accelerator_t, modifiers) - 0usize];
    ["Offset of field: native_keyboard_accelerator_t::key"]
        [::std::mem::offset_of!(native_keyboard_accelerator_t, key) - 4usize];
};
#[doc = " Menu item clicked event"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_menu_item_clicked_event_t {
    pub item_id: native_menu_item_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_menu_item_clicked_event_t"]
        [::std::mem::size_of::<native_menu_item_clicked_event_t>() - 8usize];
    ["Alignment of native_menu_item_clicked_event_t"]
        [::std::mem::align_of::<native_menu_item_clicked_event_t>() - 8usize];
    ["Offset of field: native_menu_item_clicked_event_t::item_id"]
        [::std::mem::offset_of!(native_menu_item_clicked_event_t, item_id) - 0usize];
};
#[doc = " Menu item submenu opened event"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_menu_item_submenu_opened_event_t {
    pub item_id: native_menu_item_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_menu_item_submenu_opened_event_t"]
        [::std::mem::size_of::<native_menu_item_submenu_opened_event_t>() - 8usize];
    ["Alignment of native_menu_item_submenu_opened_event_t"]
        [::std::mem::align_of::<native_menu_item_submenu_opened_event_t>() - 8usize];
    ["Offset of field: native_menu_item_submenu_opened_event_t::item_id"]
        [::std::mem::offset_of!(native_menu_item_submenu_opened_event_t, item_id) - 0usize];
};
#[doc = " Menu item submenu closed event"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_menu_item_submenu_closed_event_t {
    pub item_id: native_menu_item_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_menu_item_submenu_closed_event_t"]
        [::std::mem::size_of::<native_menu_item_submenu_closed_event_t>() - 8usize];
    ["Alignment of native_menu_item_submenu_closed_event_t"]
        [::std::mem::align_of::<native_menu_item_submenu_closed_event_t>() - 8usize];
    ["Offset of field: native_menu_item_submenu_closed_event_t::item_id"]
        [::std::mem::offset_of!(native_menu_item_submenu_closed_event_t, item_id) - 0usize];
};
#[doc = " Menu item list structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_menu_item_list_t {
    pub items: *mut native_menu_item_t,
    pub count: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_menu_item_list_t"][::std::mem::size_of::<native_menu_item_list_t>() - 16usize];
    ["Alignment of native_menu_item_list_t"]
        [::std::mem::align_of::<native_menu_item_list_t>() - 8usize];
    ["Offset of field: native_menu_item_list_t::items"]
        [::std::mem::offset_of!(native_menu_item_list_t, items) - 0usize];
    ["Offset of field: native_menu_item_list_t::count"]
        [::std::mem::offset_of!(native_menu_item_list_t, count) - 8usize];
};
#[doc = " Menu opened event"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_menu_opened_event_t {
    pub menu_id: native_menu_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_menu_opened_event_t"]
        [::std::mem::size_of::<native_menu_opened_event_t>() - 8usize];
    ["Alignment of native_menu_opened_event_t"]
        [::std::mem::align_of::<native_menu_opened_event_t>() - 8usize];
    ["Offset of field: native_menu_opened_event_t::menu_id"]
        [::std::mem::offset_of!(native_menu_opened_event_t, menu_id) - 0usize];
};
#[doc = " Menu closed event"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_menu_closed_event_t {
    pub menu_id: native_menu_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_menu_closed_event_t"]
        [::std::mem::size_of::<native_menu_closed_event_t>() - 8usize];
    ["Alignment of native_menu_closed_event_t"]
        [::std::mem::align_of::<native_menu_closed_event_t>() - 8usize];
    ["Offset of field: native_menu_closed_event_t::menu_id"]
        [::std::mem::offset_of!(native_menu_closed_event_t, menu_id) - 0usize];
};
#[doc = " Event listener registration function types"]
pub type native_menu_item_event_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        event: *const ::std::os::raw::c_void,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type native_menu_event_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        event: *const ::std::os::raw::c_void,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub const native_menu_item_event_type_t_NATIVE_MENU_ITEM_EVENT_CLICKED:
    native_menu_item_event_type_t = 0;
pub const native_menu_item_event_type_t_NATIVE_MENU_ITEM_EVENT_SUBMENU_OPENED:
    native_menu_item_event_type_t = 1;
pub const native_menu_item_event_type_t_NATIVE_MENU_ITEM_EVENT_SUBMENU_CLOSED:
    native_menu_item_event_type_t = 2;
#[doc = " Event types for menu item events"]
pub type native_menu_item_event_type_t = ::std::os::raw::c_uint;
pub const native_menu_event_type_t_NATIVE_MENU_EVENT_OPENED: native_menu_event_type_t = 0;
pub const native_menu_event_type_t_NATIVE_MENU_EVENT_CLOSED: native_menu_event_type_t = 1;
#[doc = " Event types for menu events"]
pub type native_menu_event_type_t = ::std::os::raw::c_uint;
unsafe extern "C" {
    #[doc = " Create a new menu item\n @param label The display label for the menu item\n @param type The type of menu item to create\n @return Menu item handle, or NULL if creation failed"]
    pub fn native_menu_item_create(
        label: *const ::std::os::raw::c_char,
        type_: native_menu_item_type_t,
    ) -> native_menu_item_t;
}
unsafe extern "C" {
    #[doc = " Create a separator menu item\n @return Menu item handle, or NULL if creation failed"]
    pub fn native_menu_item_create_separator() -> native_menu_item_t;
}
unsafe extern "C" {
    #[doc = " Destroy a menu item and release its resources\n @param item The menu item to destroy"]
    pub fn native_menu_item_destroy(item: native_menu_item_t);
}
unsafe extern "C" {
    #[doc = " Get the ID of a menu item\n @param item The menu item\n @return The menu item ID"]
    pub fn native_menu_item_get_id(item: native_menu_item_t) -> native_menu_item_id_t;
}
unsafe extern "C" {
    #[doc = " Get the type of a menu item\n @param item The menu item\n @return The menu item type"]
    pub fn native_menu_item_get_type(item: native_menu_item_t) -> native_menu_item_type_t;
}
unsafe extern "C" {
    #[doc = " Set the label of a menu item\n @param item The menu item\n @param label The label to set"]
    pub fn native_menu_item_set_label(
        item: native_menu_item_t,
        label: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[doc = " Get the label of a menu item\n @param item The menu item\n @return The label string (caller must free), or NULL if item is invalid"]
    pub fn native_menu_item_get_label(item: native_menu_item_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Set the icon of a menu item using an Image object\n @param item The menu item\n @param image The Image object to set as the icon, or NULL to clear the icon"]
    pub fn native_menu_item_set_icon(item: native_menu_item_t, image: native_image_t);
}
unsafe extern "C" {
    #[doc = " Get the current icon image of the menu item\n @param item The menu item\n @return The Image object, or NULL if no icon is set. Caller must call\n         native_image_destroy() when done."]
    pub fn native_menu_item_get_icon(item: native_menu_item_t) -> native_image_t;
}
unsafe extern "C" {
    #[doc = " Set the tooltip of a menu item\n @param item The menu item\n @param tooltip The tooltip text to set"]
    pub fn native_menu_item_set_tooltip(
        item: native_menu_item_t,
        tooltip: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[doc = " Get the tooltip of a menu item\n @param item The menu item\n @return The tooltip string (caller must free), or NULL if item is invalid or no tooltip set"]
    pub fn native_menu_item_get_tooltip(item: native_menu_item_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Set the keyboard accelerator for a menu item\n @param item The menu item\n @param accelerator The keyboard accelerator to set, or NULL to remove the accelerator"]
    pub fn native_menu_item_set_accelerator(
        item: native_menu_item_t,
        accelerator: *const native_keyboard_accelerator_t,
    );
}
unsafe extern "C" {
    #[doc = " Get the keyboard accelerator of a menu item\n @param item The menu item\n @param accelerator Pointer to store the accelerator (caller allocated)\n @return true if accelerator exists, false otherwise"]
    pub fn native_menu_item_get_accelerator(
        item: native_menu_item_t,
        accelerator: *mut native_keyboard_accelerator_t,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Set the enabled state of a menu item\n @param item The menu item\n @param enabled true to enable, false to disable"]
    pub fn native_menu_item_set_enabled(item: native_menu_item_t, enabled: bool);
}
unsafe extern "C" {
    #[doc = " Check if a menu item is enabled\n @param item The menu item\n @return true if enabled, false otherwise"]
    pub fn native_menu_item_is_enabled(item: native_menu_item_t) -> bool;
}
unsafe extern "C" {
    #[doc = " Set the state of a checkbox/radio menu item\n @param item The menu item\n @param state The state to set (unchecked, checked, or mixed)"]
    pub fn native_menu_item_set_state(item: native_menu_item_t, state: native_menu_item_state_t);
}
unsafe extern "C" {
    #[doc = " Get the state of a menu item\n @param item The menu item\n @return The current state of the menu item"]
    pub fn native_menu_item_get_state(item: native_menu_item_t) -> native_menu_item_state_t;
}
unsafe extern "C" {
    #[doc = " Set the radio group ID for a radio menu item\n @param item The menu item\n @param group_id The radio group identifier"]
    pub fn native_menu_item_set_radio_group(
        item: native_menu_item_t,
        group_id: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    #[doc = " Get the radio group ID of a menu item\n @param item The menu item\n @return The radio group ID, or -1 if not set"]
    pub fn native_menu_item_get_radio_group(item: native_menu_item_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Set the submenu for a menu item\n @param item The menu item\n @param submenu The submenu to attach, or NULL to remove the submenu"]
    pub fn native_menu_item_set_submenu(item: native_menu_item_t, submenu: native_menu_t);
}
unsafe extern "C" {
    #[doc = " Get the submenu of a menu item\n @param item The menu item\n @return The submenu handle, or NULL if no submenu"]
    pub fn native_menu_item_get_submenu(item: native_menu_item_t) -> native_menu_t;
}
unsafe extern "C" {
    #[doc = " Add event listener for a menu item\n @param item The menu item\n @param event_type The type of event to listen for\n @param callback The callback function\n @param user_data User data passed to callback\n @return A listener ID that can be used to remove the listener, or -1 on error"]
    pub fn native_menu_item_add_listener(
        item: native_menu_item_t,
        event_type: native_menu_item_event_type_t,
        callback: native_menu_item_event_callback_t,
        user_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Remove event listener from a menu item\n @param item The menu item\n @param listener_id The listener ID returned by native_menu_item_add_listener\n @return true if removed successfully, false otherwise"]
    pub fn native_menu_item_remove_listener(
        item: native_menu_item_t,
        listener_id: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Create a new menu\n @return Menu handle, or NULL if creation failed"]
    pub fn native_menu_create() -> native_menu_t;
}
unsafe extern "C" {
    #[doc = " Destroy a menu and release its resources\n @param menu The menu to destroy"]
    pub fn native_menu_destroy(menu: native_menu_t);
}
unsafe extern "C" {
    #[doc = " Get the ID of a menu\n @param menu The menu\n @return The menu ID"]
    pub fn native_menu_get_id(menu: native_menu_t) -> native_menu_id_t;
}
unsafe extern "C" {
    #[doc = " Add a menu item to the end of the menu\n @param menu The menu\n @param item The menu item to add"]
    pub fn native_menu_add_item(menu: native_menu_t, item: native_menu_item_t);
}
unsafe extern "C" {
    #[doc = " Insert a menu item at a specific position\n @param menu The menu\n @param item The menu item to insert\n @param index The position to insert at (0-based)"]
    pub fn native_menu_insert_item(menu: native_menu_t, item: native_menu_item_t, index: usize);
}
unsafe extern "C" {
    #[doc = " Remove a menu item from the menu\n @param menu The menu\n @param item The menu item to remove\n @return true if item was found and removed, false otherwise"]
    pub fn native_menu_remove_item(menu: native_menu_t, item: native_menu_item_t) -> bool;
}
unsafe extern "C" {
    #[doc = " Remove a menu item by its ID\n @param menu The menu\n @param item_id The ID of the item to remove\n @return true if item was found and removed, false otherwise"]
    pub fn native_menu_remove_item_by_id(
        menu: native_menu_t,
        item_id: native_menu_item_id_t,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Remove a menu item at a specific position\n @param menu The menu\n @param index The position of the item to remove (0-based)\n @return true if item was removed, false if index out of bounds"]
    pub fn native_menu_remove_item_at(menu: native_menu_t, index: usize) -> bool;
}
unsafe extern "C" {
    #[doc = " Remove all items from the menu\n @param menu The menu"]
    pub fn native_menu_clear(menu: native_menu_t);
}
unsafe extern "C" {
    #[doc = " Add a separator to the end of the menu\n @param menu The menu"]
    pub fn native_menu_add_separator(menu: native_menu_t);
}
unsafe extern "C" {
    #[doc = " Insert a separator at a specific position\n @param menu The menu\n @param index The position to insert the separator at (0-based)"]
    pub fn native_menu_insert_separator(menu: native_menu_t, index: usize);
}
unsafe extern "C" {
    #[doc = " Get the number of items in the menu\n @param menu The menu\n @return The number of items"]
    pub fn native_menu_get_item_count(menu: native_menu_t) -> usize;
}
unsafe extern "C" {
    #[doc = " Get a menu item at a specific position\n @param menu The menu\n @param index The position of the item (0-based)\n @return The menu item handle, or NULL if index out of bounds"]
    pub fn native_menu_get_item_at(menu: native_menu_t, index: usize) -> native_menu_item_t;
}
unsafe extern "C" {
    #[doc = " Get a menu item by its ID\n @param menu The menu\n @param item_id The ID of the item to find\n @return The menu item handle, or NULL if not found"]
    pub fn native_menu_get_item_by_id(
        menu: native_menu_t,
        item_id: native_menu_item_id_t,
    ) -> native_menu_item_t;
}
unsafe extern "C" {
    #[doc = " Get all menu items\n @param menu The menu\n @return List of menu items (caller must free with native_menu_item_list_free)"]
    pub fn native_menu_get_all_items(menu: native_menu_t) -> native_menu_item_list_t;
}
unsafe extern "C" {
    #[doc = " Open the menu as a context menu using the specified positioning strategy\n @param menu The menu\n @param strategy The positioning strategy determining where to display the menu\n @param placement The placement option determining how the menu is positioned\n                  relative to the reference point (default: NATIVE_PLACEMENT_BOTTOM_START)\n @return true if menu was opened successfully, false otherwise"]
    pub fn native_menu_open(
        menu: native_menu_t,
        strategy: native_positioning_strategy_t,
        placement: native_placement_t,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Close the menu if it's currently showing\n @param menu The menu\n @return true if menu was closed, false otherwise"]
    pub fn native_menu_close(menu: native_menu_t) -> bool;
}
unsafe extern "C" {
    #[doc = " Add event listener for a menu\n @param menu The menu\n @param event_type The type of event to listen for\n @param callback The callback function\n @param user_data User data passed to callback\n @return A listener ID that can be used to remove the listener, or -1 on error"]
    pub fn native_menu_add_listener(
        menu: native_menu_t,
        event_type: native_menu_event_type_t,
        callback: native_menu_event_callback_t,
        user_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Remove event listener from a menu\n @param menu The menu\n @param listener_id The listener ID returned by native_menu_add_listener\n @return true if removed successfully, false otherwise"]
    pub fn native_menu_remove_listener(
        menu: native_menu_t,
        listener_id: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Free a menu item list\n @param list The list to free"]
    pub fn native_menu_item_list_free(list: native_menu_item_list_t);
}
unsafe extern "C" {
    #[doc = " Convert keyboard accelerator to string representation\n @param accelerator The accelerator\n @return The string representation (caller must free), or NULL if accelerator is invalid"]
    pub fn native_keyboard_accelerator_to_string(
        accelerator: *const native_keyboard_accelerator_t,
    ) -> *mut ::std::os::raw::c_char;
}
pub type native_preferences_t = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    #[doc = " @brief Create a preferences storage with default scope.\n @return Handle to preferences storage, or NULL on failure"]
    pub fn native_preferences_create() -> native_preferences_t;
}
unsafe extern "C" {
    #[doc = " @brief Create a preferences storage with custom scope.\n @param scope Scope for isolating preferences\n @return Handle to preferences storage, or NULL on failure"]
    pub fn native_preferences_create_with_scope(
        scope: *const ::std::os::raw::c_char,
    ) -> native_preferences_t;
}
unsafe extern "C" {
    #[doc = " @brief Destroy a preferences storage instance.\n @param prefs Handle to preferences storage"]
    pub fn native_preferences_destroy(prefs: native_preferences_t);
}
unsafe extern "C" {
    #[doc = " @brief Set a key-value pair.\n @param prefs Handle to preferences storage\n @param key The key to set\n @param value The value to store\n @return true if successful, false otherwise"]
    pub fn native_preferences_set(
        prefs: native_preferences_t,
        key: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Get the value for a given key.\n @param prefs Handle to preferences storage\n @param key The key to retrieve\n @param default_value Default value if key doesn't exist\n @return The stored value or default_value. Caller must free the returned string."]
    pub fn native_preferences_get(
        prefs: native_preferences_t,
        key: *const ::std::os::raw::c_char,
        default_value: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " @brief Remove a key-value pair.\n @param prefs Handle to preferences storage\n @param key The key to remove\n @return true if successful, false if key doesn't exist"]
    pub fn native_preferences_remove(
        prefs: native_preferences_t,
        key: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Clear all key-value pairs.\n @param prefs Handle to preferences storage\n @return true if successful, false otherwise"]
    pub fn native_preferences_clear(prefs: native_preferences_t) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Check if a key exists.\n @param prefs Handle to preferences storage\n @param key The key to check\n @return true if key exists, false otherwise"]
    pub fn native_preferences_contains(
        prefs: native_preferences_t,
        key: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Get all keys.\n @param prefs Handle to preferences storage\n @param out_keys Pointer to array of keys (allocated by function)\n @param out_count Pointer to receive number of keys\n @return true if successful, false otherwise. Caller must free each key and the array."]
    pub fn native_preferences_get_keys(
        prefs: native_preferences_t,
        out_keys: *mut *mut *mut ::std::os::raw::c_char,
        out_count: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Get the number of stored items.\n @param prefs Handle to preferences storage\n @return Number of key-value pairs"]
    pub fn native_preferences_get_size(prefs: native_preferences_t) -> usize;
}
unsafe extern "C" {
    #[doc = " @brief Get the scope.\n @param prefs Handle to preferences storage\n @return The scope. Caller must free the returned string."]
    pub fn native_preferences_get_scope(prefs: native_preferences_t)
        -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " @brief Free a string returned by preferences functions.\n @param str String to free"]
    pub fn native_preferences_free_string(str_: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[doc = " @brief Free a string array returned by preferences functions.\n @param strings Array of strings to free\n @param count Number of strings in the array"]
    pub fn native_preferences_free_string_array(
        strings: *mut *mut ::std::os::raw::c_char,
        count: usize,
    );
}
unsafe extern "C" {
    #[doc = " Run the application with the default window.\n This function starts the main event loop and blocks until the application\n exits.\n\n @return Exit code of the application (0 for success)"]
    pub fn native_run_example_app() -> ::std::os::raw::c_int;
}
pub type native_secure_storage_t = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    #[doc = " @brief Create a secure storage with default scope.\n @return Handle to secure storage, or NULL on failure"]
    pub fn native_secure_storage_create() -> native_secure_storage_t;
}
unsafe extern "C" {
    #[doc = " @brief Create a secure storage with custom scope.\n @param scope Scope/application identifier\n @return Handle to secure storage, or NULL on failure"]
    pub fn native_secure_storage_create_with_scope(
        scope: *const ::std::os::raw::c_char,
    ) -> native_secure_storage_t;
}
unsafe extern "C" {
    #[doc = " @brief Destroy a secure storage instance.\n @param storage Handle to secure storage"]
    pub fn native_secure_storage_destroy(storage: native_secure_storage_t);
}
unsafe extern "C" {
    #[doc = " @brief Set a key-value pair in secure storage.\n @param storage Handle to secure storage\n @param key The key to set\n @param value The value to store\n @return true if successful, false otherwise"]
    pub fn native_secure_storage_set(
        storage: native_secure_storage_t,
        key: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Get the value for a given key from secure storage.\n @param storage Handle to secure storage\n @param key The key to retrieve\n @param default_value Default value if key doesn't exist\n @return The stored value or default_value. Caller must free the returned string."]
    pub fn native_secure_storage_get(
        storage: native_secure_storage_t,
        key: *const ::std::os::raw::c_char,
        default_value: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " @brief Remove a key-value pair from secure storage.\n @param storage Handle to secure storage\n @param key The key to remove\n @return true if successful, false if key doesn't exist"]
    pub fn native_secure_storage_remove(
        storage: native_secure_storage_t,
        key: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Clear all key-value pairs from secure storage.\n @param storage Handle to secure storage\n @return true if successful, false otherwise"]
    pub fn native_secure_storage_clear(storage: native_secure_storage_t) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Check if a key exists in secure storage.\n @param storage Handle to secure storage\n @param key The key to check\n @return true if key exists, false otherwise"]
    pub fn native_secure_storage_contains(
        storage: native_secure_storage_t,
        key: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Get all keys from secure storage.\n @param storage Handle to secure storage\n @param out_keys Pointer to array of keys (allocated by function)\n @param out_count Pointer to receive number of keys\n @return true if successful, false otherwise. Caller must free each key and the array."]
    pub fn native_secure_storage_get_keys(
        storage: native_secure_storage_t,
        out_keys: *mut *mut *mut ::std::os::raw::c_char,
        out_count: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Get the number of stored items in secure storage.\n @param storage Handle to secure storage\n @return Number of key-value pairs"]
    pub fn native_secure_storage_get_size(storage: native_secure_storage_t) -> usize;
}
unsafe extern "C" {
    #[doc = " @brief Get the scope.\n @param storage Handle to secure storage\n @return The scope. Caller must free the returned string."]
    pub fn native_secure_storage_get_scope(
        storage: native_secure_storage_t,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " @brief Check if secure storage is available on this platform.\n @return true if platform supports secure storage, false otherwise"]
    pub fn native_secure_storage_is_available() -> bool;
}
unsafe extern "C" {
    #[doc = " @brief Free a string returned by secure storage functions.\n @param str String to free"]
    pub fn native_secure_storage_free_string(str_: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[doc = " @brief Free a string array returned by secure storage functions.\n @param strings Array of strings to free\n @param count Number of strings in the array"]
    pub fn native_secure_storage_free_string_array(
        strings: *mut *mut ::std::os::raw::c_char,
        count: usize,
    );
}
unsafe extern "C" {
    #[doc = " Free a C string allocated by to_c_str\n @param str The string to free (can be nullptr)"]
    pub fn free_c_str(str_: *mut ::std::os::raw::c_char);
}
#[doc = " Opaque handle for tray icon objects"]
pub type native_tray_icon_t = *mut ::std::os::raw::c_void;
#[doc = " Tray icon identifier"]
pub type native_tray_icon_id_t = ::std::os::raw::c_long;
#[doc = " Tray icon clicked event"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_tray_icon_clicked_event_t {
    pub tray_icon_id: native_tray_icon_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_tray_icon_clicked_event_t"]
        [::std::mem::size_of::<native_tray_icon_clicked_event_t>() - 8usize];
    ["Alignment of native_tray_icon_clicked_event_t"]
        [::std::mem::align_of::<native_tray_icon_clicked_event_t>() - 8usize];
    ["Offset of field: native_tray_icon_clicked_event_t::tray_icon_id"]
        [::std::mem::offset_of!(native_tray_icon_clicked_event_t, tray_icon_id) - 0usize];
};
#[doc = " Tray icon right-clicked event"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_tray_icon_right_clicked_event_t {
    pub tray_icon_id: native_tray_icon_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_tray_icon_right_clicked_event_t"]
        [::std::mem::size_of::<native_tray_icon_right_clicked_event_t>() - 8usize];
    ["Alignment of native_tray_icon_right_clicked_event_t"]
        [::std::mem::align_of::<native_tray_icon_right_clicked_event_t>() - 8usize];
    ["Offset of field: native_tray_icon_right_clicked_event_t::tray_icon_id"]
        [::std::mem::offset_of!(native_tray_icon_right_clicked_event_t, tray_icon_id) - 0usize];
};
#[doc = " Tray icon double-clicked event"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_tray_icon_double_clicked_event_t {
    pub tray_icon_id: native_tray_icon_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_tray_icon_double_clicked_event_t"]
        [::std::mem::size_of::<native_tray_icon_double_clicked_event_t>() - 8usize];
    ["Alignment of native_tray_icon_double_clicked_event_t"]
        [::std::mem::align_of::<native_tray_icon_double_clicked_event_t>() - 8usize];
    ["Offset of field: native_tray_icon_double_clicked_event_t::tray_icon_id"]
        [::std::mem::offset_of!(native_tray_icon_double_clicked_event_t, tray_icon_id) - 0usize];
};
pub const native_tray_icon_event_type_t_NATIVE_TRAY_ICON_EVENT_CLICKED:
    native_tray_icon_event_type_t = 0;
pub const native_tray_icon_event_type_t_NATIVE_TRAY_ICON_EVENT_RIGHT_CLICKED:
    native_tray_icon_event_type_t = 1;
pub const native_tray_icon_event_type_t_NATIVE_TRAY_ICON_EVENT_DOUBLE_CLICKED:
    native_tray_icon_event_type_t = 2;
#[doc = " Event types for tray icon events"]
pub type native_tray_icon_event_type_t = ::std::os::raw::c_uint;
pub const native_context_menu_trigger_t_NATIVE_CONTEXT_MENU_TRIGGER_NONE:
    native_context_menu_trigger_t = 0;
pub const native_context_menu_trigger_t_NATIVE_CONTEXT_MENU_TRIGGER_CLICKED:
    native_context_menu_trigger_t = 1;
pub const native_context_menu_trigger_t_NATIVE_CONTEXT_MENU_TRIGGER_RIGHT_CLICKED:
    native_context_menu_trigger_t = 2;
pub const native_context_menu_trigger_t_NATIVE_CONTEXT_MENU_TRIGGER_DOUBLE_CLICKED:
    native_context_menu_trigger_t = 3;
#[doc = " Context menu trigger modes\n Defines how the context menu is triggered for a tray icon"]
pub type native_context_menu_trigger_t = ::std::os::raw::c_uint;
#[doc = " Event callback function type"]
pub type native_tray_icon_event_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        event: *const ::std::os::raw::c_void,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    #[doc = " Create a new tray icon\n @return Tray icon handle, or NULL if creation failed"]
    pub fn native_tray_icon_create() -> native_tray_icon_t;
}
unsafe extern "C" {
    #[doc = " Create a tray icon from a native platform object\n @param native_tray Pointer to platform-specific tray icon object\n @return Tray icon handle, or NULL if creation failed"]
    pub fn native_tray_icon_create_from_native(
        native_tray: *mut ::std::os::raw::c_void,
    ) -> native_tray_icon_t;
}
unsafe extern "C" {
    #[doc = " Destroy a tray icon and release its resources\n @param tray_icon The tray icon to destroy"]
    pub fn native_tray_icon_destroy(tray_icon: native_tray_icon_t);
}
unsafe extern "C" {
    #[doc = " Get the ID of a tray icon\n @param tray_icon The tray icon\n @return The tray icon ID"]
    pub fn native_tray_icon_get_id(tray_icon: native_tray_icon_t) -> native_tray_icon_id_t;
}
unsafe extern "C" {
    #[doc = " Set the icon image for the tray icon using an Image object\n @param tray_icon The tray icon\n @param image The Image object to set as the icon, or NULL to clear the icon"]
    pub fn native_tray_icon_set_icon(tray_icon: native_tray_icon_t, image: native_image_t);
}
unsafe extern "C" {
    #[doc = " Get the current icon image of the tray icon\n @param tray_icon The tray icon\n @return The Image object, or NULL if no icon is set. Caller must call\n         native_image_destroy() when done."]
    pub fn native_tray_icon_get_icon(tray_icon: native_tray_icon_t) -> native_image_t;
}
unsafe extern "C" {
    #[doc = " Set the title text for the tray icon\n @param tray_icon The tray icon\n @param title The title text to set, or NULL to clear the title"]
    pub fn native_tray_icon_set_title(
        tray_icon: native_tray_icon_t,
        title: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[doc = " Get the title text of the tray icon\n @param tray_icon The tray icon\n @return The title text, or NULL if no title is set or error. Caller must free\n the returned string."]
    pub fn native_tray_icon_get_title(tray_icon: native_tray_icon_t)
        -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Set the tooltip text for the tray icon\n @param tray_icon The tray icon\n @param tooltip The tooltip text to set, or NULL to clear the tooltip"]
    pub fn native_tray_icon_set_tooltip(
        tray_icon: native_tray_icon_t,
        tooltip: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[doc = " Get the tooltip text of the tray icon\n @param tray_icon The tray icon\n @return The tooltip text, or NULL if no tooltip is set or error. Caller must\n free the returned string."]
    pub fn native_tray_icon_get_tooltip(
        tray_icon: native_tray_icon_t,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Set the context menu for the tray icon\n @param tray_icon The tray icon\n @param menu The context menu to set"]
    pub fn native_tray_icon_set_context_menu(tray_icon: native_tray_icon_t, menu: native_menu_t);
}
unsafe extern "C" {
    #[doc = " Get the context menu of the tray icon\n @param tray_icon The tray icon\n @return The context menu handle, or NULL if no menu set"]
    pub fn native_tray_icon_get_context_menu(tray_icon: native_tray_icon_t) -> native_menu_t;
}
unsafe extern "C" {
    #[doc = " Set the context menu trigger behavior\n @param tray_icon The tray icon\n @param trigger The desired trigger behavior"]
    pub fn native_tray_icon_set_context_menu_trigger(
        tray_icon: native_tray_icon_t,
        trigger: native_context_menu_trigger_t,
    );
}
unsafe extern "C" {
    #[doc = " Get the current context menu trigger behavior\n @param tray_icon The tray icon\n @return The current trigger behavior"]
    pub fn native_tray_icon_get_context_menu_trigger(
        tray_icon: native_tray_icon_t,
    ) -> native_context_menu_trigger_t;
}
unsafe extern "C" {
    #[doc = " Get the screen bounds of the tray icon\n @param tray_icon The tray icon\n @param bounds Pointer to store the bounds (caller allocated)\n @return true if bounds were retrieved successfully, false otherwise"]
    pub fn native_tray_icon_get_bounds(
        tray_icon: native_tray_icon_t,
        bounds: *mut native_rectangle_t,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Set the visibility of the tray icon in the system tray\n @param tray_icon The tray icon\n @param visible true to show the icon, false to hide it\n @return true if visibility was changed successfully, false otherwise"]
    pub fn native_tray_icon_set_visible(tray_icon: native_tray_icon_t, visible: bool) -> bool;
}
unsafe extern "C" {
    #[doc = " Check if the tray icon is currently visible\n @param tray_icon The tray icon\n @return true if visible, false otherwise"]
    pub fn native_tray_icon_is_visible(tray_icon: native_tray_icon_t) -> bool;
}
unsafe extern "C" {
    #[doc = " Add an event listener for tray icon events\n @param tray_icon The tray icon\n @param event_type The type of event to listen for\n @param callback The callback function\n @param user_data User data to pass to callback\n @return Listener ID that can be used to remove the listener, or -1 on error"]
    pub fn native_tray_icon_add_listener(
        tray_icon: native_tray_icon_t,
        event_type: native_tray_icon_event_type_t,
        callback: native_tray_icon_event_callback_t,
        user_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Remove an event listener\n @param tray_icon The tray icon\n @param listener_id The listener ID returned by add_listener\n @return true if the listener was found and removed, false otherwise"]
    pub fn native_tray_icon_remove_listener(
        tray_icon: native_tray_icon_t,
        listener_id: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Open the context menu at default location\n @param tray_icon The tray icon\n @return true if menu was opened successfully, false otherwise"]
    pub fn native_tray_icon_open_context_menu(tray_icon: native_tray_icon_t) -> bool;
}
unsafe extern "C" {
    #[doc = " Close the currently displayed context menu\n @param tray_icon The tray icon\n @return true if menu was closed successfully or wasn't visible, false on\n error"]
    pub fn native_tray_icon_close_context_menu(tray_icon: native_tray_icon_t) -> bool;
}
#[doc = " Tray icon list structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_tray_icon_list_t {
    pub tray_icons: *mut native_tray_icon_t,
    pub count: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_tray_icon_list_t"][::std::mem::size_of::<native_tray_icon_list_t>() - 16usize];
    ["Alignment of native_tray_icon_list_t"]
        [::std::mem::align_of::<native_tray_icon_list_t>() - 8usize];
    ["Offset of field: native_tray_icon_list_t::tray_icons"]
        [::std::mem::offset_of!(native_tray_icon_list_t, tray_icons) - 0usize];
    ["Offset of field: native_tray_icon_list_t::count"]
        [::std::mem::offset_of!(native_tray_icon_list_t, count) - 8usize];
};
unsafe extern "C" {
    #[doc = " Check if system tray is supported on the current platform\n @return true if system tray is supported, false otherwise"]
    pub fn native_tray_manager_is_supported() -> bool;
}
unsafe extern "C" {
    #[doc = " Get a tray icon by its ID\n @param tray_icon_id The tray icon ID\n @return Tray icon handle, or NULL if not found"]
    pub fn native_tray_manager_get(tray_icon_id: native_tray_icon_id_t) -> native_tray_icon_t;
}
unsafe extern "C" {
    #[doc = " Get all managed tray icons\n @return List of all tray icons (caller must free with native_tray_icon_list_free)"]
    pub fn native_tray_manager_get_all() -> native_tray_icon_list_t;
}
unsafe extern "C" {
    #[doc = " Free a tray icon list\n @param list The list to free"]
    pub fn native_tray_icon_list_free(list: native_tray_icon_list_t);
}
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_CREATED: native_window_event_type_t = 0;
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_CLOSED: native_window_event_type_t = 1;
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_FOCUSED: native_window_event_type_t = 2;
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_BLURRED: native_window_event_type_t = 3;
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_MINIMIZED: native_window_event_type_t = 4;
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_MAXIMIZED: native_window_event_type_t = 5;
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_RESTORED: native_window_event_type_t = 6;
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_MOVED: native_window_event_type_t = 7;
pub const native_window_event_type_t_NATIVE_WINDOW_EVENT_RESIZED: native_window_event_type_t = 8;
#[doc = " Window event types"]
pub type native_window_event_type_t = ::std::os::raw::c_uint;
#[doc = " Window event structure"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct native_window_event_t {
    pub type_: native_window_event_type_t,
    pub window_id: native_window_id_t,
    pub data: native_window_event_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union native_window_event_t__bindgen_ty_1 {
    pub moved: native_window_event_t__bindgen_ty_1__bindgen_ty_1,
    pub resized: native_window_event_t__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_window_event_t__bindgen_ty_1__bindgen_ty_1 {
    pub position: native_point_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_window_event_t__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<native_window_event_t__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of native_window_event_t__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<native_window_event_t__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: native_window_event_t__bindgen_ty_1__bindgen_ty_1::position"][::std::mem::offset_of!(
        native_window_event_t__bindgen_ty_1__bindgen_ty_1,
        position
    ) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct native_window_event_t__bindgen_ty_1__bindgen_ty_2 {
    pub size: native_size_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_window_event_t__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<native_window_event_t__bindgen_ty_1__bindgen_ty_2>() - 16usize];
    ["Alignment of native_window_event_t__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<native_window_event_t__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Offset of field: native_window_event_t__bindgen_ty_1__bindgen_ty_2::size"]
        [::std::mem::offset_of!(native_window_event_t__bindgen_ty_1__bindgen_ty_2, size) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_window_event_t__bindgen_ty_1"]
        [::std::mem::size_of::<native_window_event_t__bindgen_ty_1>() - 16usize];
    ["Alignment of native_window_event_t__bindgen_ty_1"]
        [::std::mem::align_of::<native_window_event_t__bindgen_ty_1>() - 8usize];
    ["Offset of field: native_window_event_t__bindgen_ty_1::moved"]
        [::std::mem::offset_of!(native_window_event_t__bindgen_ty_1, moved) - 0usize];
    ["Offset of field: native_window_event_t__bindgen_ty_1::resized"]
        [::std::mem::offset_of!(native_window_event_t__bindgen_ty_1, resized) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of native_window_event_t"][::std::mem::size_of::<native_window_event_t>() - 32usize];
    ["Alignment of native_window_event_t"]
        [::std::mem::align_of::<native_window_event_t>() - 8usize];
    ["Offset of field: native_window_event_t::type_"]
        [::std::mem::offset_of!(native_window_event_t, type_) - 0usize];
    ["Offset of field: native_window_event_t::window_id"]
        [::std::mem::offset_of!(native_window_event_t, window_id) - 8usize];
    ["Offset of field: native_window_event_t::data"]
        [::std::mem::offset_of!(native_window_event_t, data) - 16usize];
};
#[doc = " Window event callback function type"]
pub type native_window_event_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        event: *const native_window_event_t,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    #[doc = " Create a new window with the specified options\n @param options Window creation options\n @return Window handle, or NULL if creation failed"]
    pub fn native_window_manager_create(options: *const native_window_options_t)
        -> native_window_t;
}
unsafe extern "C" {
    #[doc = " Get a window by its ID\n @param window_id The window ID\n @return Window handle, or NULL if not found"]
    pub fn native_window_manager_get(window_id: native_window_id_t) -> native_window_t;
}
unsafe extern "C" {
    #[doc = " Get all managed windows\n @return List of all windows (caller must free with native_window_list_free)"]
    pub fn native_window_manager_get_all() -> native_window_list_t;
}
unsafe extern "C" {
    #[doc = " Get the currently active/focused window\n @return Current window handle, or NULL if no window is active"]
    pub fn native_window_manager_get_current() -> native_window_t;
}
unsafe extern "C" {
    #[doc = " Destroy a window by its ID\n @param window_id The window ID to destroy\n @return true if window was found and destroyed, false otherwise"]
    pub fn native_window_manager_destroy(window_id: native_window_id_t) -> bool;
}
unsafe extern "C" {
    #[doc = " Register a callback for window events\n @param callback The callback function to register\n @param user_data User data to pass to the callback\n @return Registration ID, or -1 on failure"]
    pub fn native_window_manager_register_event_callback(
        callback: native_window_event_callback_t,
        user_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Unregister a window event callback\n @param registration_id The registration ID returned by register_event_callback\n @return true if callback was found and unregistered, false otherwise"]
    pub fn native_window_manager_unregister_event_callback(
        registration_id: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Shutdown the window manager and cleanup resources"]
    pub fn native_window_manager_shutdown();
}
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
