name: nativeapi
description: "Dart bindings for nativeapi - providing seamless, unified access to native system APIs."
version: 0.3.1
homepage: https://github.com/libnativeapi/nativeapi-flutter
resolution: workspace

environment:
  sdk: ^3.13.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  cnativeapi: ^0.3.1
  ffi: ">=1.2.1 <3.0.0"

dev_dependencies:
  lints: ^5.1.1
