// =============================================================================
// Auto-generated Rust wrapper for: url_opener.h
// Generated by bindgen
// =============================================================================

#![allow(dead_code)]
#![allow(non_camel_case_types)]

use cnativeapi as ffi;

// Types

#[repr(C)]
pub struct UrlOpenResult {
    pub success: bool,
    pub error_code: UrlOpenErrorCode,
    pub error_message: *const ::core::ffi::c_char,
}

// Enums

#[repr(i32)]
pub enum UrlOpenErrorCode {
    kNone = 0,
    kInvalidUrlEmpty = 1,
    kInvalidUrlMissingScheme = 2,
    kInvalidUrlUnsupportedScheme = 3,
    kUnsupportedPlatform = 4,
    kInvocationFailed = 5,
}

// Class wrappers

pub struct UrlOpener {
    pub handle: *mut ::core::ffi::c_void,
}

impl UrlOpener {
    #[inline]
    pub fn is_supported() -> bool {
        unsafe { ffi::native_url_opener_is_supported() }
    }
    #[inline]
    pub fn open(&self, url: &str) -> UrlOpenResult {
        let url_native = std::ffi::CString::new(url).unwrap();
        unsafe {
            let result = ffi::native_url_opener_open(url_native.as_ptr());
            std::mem::transmute::<ffi::native_url_open_result_t, UrlOpenResult>(result)
        }
    }
}
