#!/bin/bash
# remote.sh — run things on another machine (Windows, Linux, macOS) over SSH. See ../SKILL.md.
#
#   remote.sh hosts                          list the configured hosts
#   remote.sh <host> setup                   create the scratch dir, write the env file, push the kit
#   remote.sh <host> push <file>…            copy files into the scratch dir
#   remote.sh <host> pull <name> <local>     copy a file or directory back from the scratch dir
#   remote.sh <host> exec '<snippet>'        run a snippet in the SSH session (PowerShell on Windows,
#                                            bash elsewhere), with the env file loaded
#   remote.sh <host> run <script> [args…]    push a script (.ps1 / .sh / .py) and run it in the SSH session
#   remote.sh <host> desktop <script> [timeout-seconds]
#                                            push a script and run it in the logged-on desktop session,
#                                            wait for it, print its output
#
# <host> is the name of a file in ../hosts/<host>.env (git-ignored; templates in ../hosts.example).
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
skills=$(cd "$here/../.." && pwd)
hosts_dir="$here/../hosts"

usage() { sed -n '2,15p' "$0"; exit 2; }
[ $# -ge 1 ] || usage

if [ "$1" = hosts ]; then
  for f in "$hosts_dir"/*.env; do
    [ -e "$f" ] || { echo "no hosts configured; copy a template from hosts.example/ to hosts/<name>.env" >&2; exit 1; }
    ( source "$f"; printf '%-12s %-8s %s\n' "$(basename "$f" .env)" "$HOST_OS" "$HOST_SSH" )
  done
  exit 0
fi

host=$1; cmd=${2:-}; shift 2 || usage
conf="$hosts_dir/$host.env"
[ -f "$conf" ] || { echo "unknown host '$host': $conf is missing (templates in hosts.example/)" >&2; exit 2; }
# shellcheck disable=SC1090
source "$conf"
: "${HOST_OS:?}" "${HOST_SSH:?}" "${HOST_WORKSPACE:?}" "${HOST_SCRATCH:?}"
case "$HOST_OS" in windows|linux|macos) ;; *) echo "HOST_OS must be windows, linux or macos" >&2; exit 2 ;; esac

ssh_opts=(-o BatchMode=yes -o ConnectTimeout=10)
scp_dir="$HOST_SSH:${HOST_SCRATCH//\\//}"
remote() { ssh "${ssh_opts[@]}" "$HOST_SSH" "$@"; }
push() { scp -q "${ssh_opts[@]}" "$@" "$scp_dir/"; }

# The kit: what every skill ships for this OS, by convention
#   <skill>/scripts/<os>/*   (and scripts/posix/* for Linux and macOS)   OS-specific helpers
#   <skill>/scripts/*.py                                                 portable tools
# It all lands flat in the scratch dir, so scripts find each other next to themselves.
kit_files() {
  local dirs=("$HOST_OS"); [ "$HOST_OS" = windows ] || dirs+=(posix)
  for d in "${dirs[@]}"; do find "$skills"/*/scripts/"$d" -maxdepth 1 -type f 2>/dev/null; done
  find "$skills"/*/scripts -maxdepth 1 -type f -name '*.py'
}

# Runs a pushed script in the SSH session, picking the interpreter from its extension.
run_remote() {  # <name> [args…]
  local name=$1; shift
  if [ "$HOST_OS" = windows ]; then
    case "$name" in
      *.ps1) remote "powershell -NoProfile -ExecutionPolicy Bypass -Command \"[Console]::OutputEncoding=[Text.Encoding]::UTF8; & $HOST_SCRATCH\\$name $*\"" ;;
      *.py)  remote "${HOST_PYTHON:-python} $HOST_SCRATCH\\$name $*" ;;
      *) echo "cannot run $name on Windows (.ps1 or .py)" >&2; exit 2 ;;
    esac
  else
    case "$name" in
      *.sh) remote "bash $HOST_SCRATCH/$name $*" ;;
      *.py) remote "bash -c '. $HOST_SCRATCH/env.sh; exec \"\$PYTHON\" $HOST_SCRATCH/$name $*'" ;;
      *) echo "cannot run $name on $HOST_OS (.sh or .py)" >&2; exit 2 ;;
    esac
  fi
}

case "$cmd" in
  setup)
    tmp=$(mktemp -d)
    if [ "$HOST_OS" = windows ]; then
      remote "if not exist $HOST_SCRATCH mkdir $HOST_SCRATCH" >/dev/null
      cat > "$tmp/env.ps1" <<PS
# Generated by remote.sh setup. Dot-source first: . "\$PSScriptRoot\\env.ps1"
\$RemoteWorkspace = '$HOST_WORKSPACE'
\$RemoteScratch = \$PSScriptRoot
\$Python = '${HOST_PYTHON:-python}'
if ('${HOST_PATH_PREPEND:-}') { \$env:Path = '${HOST_PATH_PREPEND:-};' + \$env:Path }
PS
      envfile="$tmp/env.ps1"
    else
      remote "mkdir -p '$HOST_SCRATCH'"
      cat > "$tmp/env.sh" <<SH
# Generated by remote.sh setup. Source first: . "\$(dirname "\$0")/env.sh"
export REMOTE_WORKSPACE='$HOST_WORKSPACE'
export REMOTE_SCRATCH='$HOST_SCRATCH'
export PYTHON='${HOST_PYTHON:-python3}'
export REMOTE_DISPLAY='${HOST_DISPLAY:-:0}'
[ -z '${HOST_PATH_PREPEND:-}' ] || export PATH='${HOST_PATH_PREPEND:-}':"\$PATH"
SH
      envfile="$tmp/env.sh"
    fi
    files=(); while IFS= read -r f; do files+=("$f"); done < <(kit_files)
    push "$envfile" "${files[@]}"
    rm -rf "$tmp"
    echo "kit pushed to $host:$HOST_SCRATCH (${#files[@]} files)"
    ;;
  push) push "$@" ;;
  pull) scp -q -r "${ssh_opts[@]}" "$scp_dir/$1" "$2" ;;
  exec)
    tmp=$(mktemp -d)
    if [ "$HOST_OS" = windows ]; then
      { echo '. "$PSScriptRoot\env.ps1"'; echo "$1"; } > "$tmp/snippet.ps1"; snippet=snippet.ps1
    else
      { echo '. "$(dirname "$0")/env.sh"'; echo "$1"; } > "$tmp/snippet.sh"; snippet=snippet.sh
    fi
    push "$tmp/$snippet"; rm -rf "$tmp"
    run_remote "$snippet"
    ;;
  run)
    script=$1; shift
    push "$script"
    run_remote "$(basename "$script")" "$@"
    ;;
  desktop)
    script=$1; timeout=${2:-600}
    push "$script"
    if [ "$HOST_OS" = windows ]; then
      run_remote interactive.ps1 "-Script $(basename "$script") -Timeout $timeout"
    else
      run_remote desktop.sh "$HOST_OS" "$(basename "$script")" "$timeout"
    fi
    ;;
  *) usage ;;
esac
