name: nativeapi
description: "Flutter bindings for nativeapi - providing seamless, unified access to native system APIs."
version: 0.1.0-dev.2
homepage: https://github.com/libnativeapi/nativeapi-flutter
resolution: workspace

environment:
  sdk: ^3.4.0
  flutter: ">=1.17.0"

dependencies:
  ffi: ">=1.2.1 <3.0.0"
  flutter:
    sdk: flutter
  cnativeapi:
    path: ../cnativeapi
  path: ^1.8.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
