name: nativeapi
description: "Flutter bindings for nativeapi - providing seamless, unified access to native system APIs."
version: 0.1.0
homepage: https://github.com/libnativeapi/nativeapi-flutter
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  ffi: ">=1.2.1 <3.0.0"
  flutter:
    sdk: flutter
  cnativeapi: ^0.1.0
  path: ^1.9.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
