#pragma once

#ifdef __cplusplus
// C++ API headers
#include "../../../../../cxx_impl/src/accessibility_manager.h"
#include "../../../../../cxx_impl/src/application.h"
#include "../../../../../cxx_impl/src/application_event.h"
#include "../../../../../cxx_impl/src/dialog.h"
#include "../../../../../cxx_impl/src/display.h"
#include "../../../../../cxx_impl/src/display_event.h"
#include "../../../../../cxx_impl/src/display_manager.h"
#include "../../../../../cxx_impl/src/foundation/event.h"
#include "../../../../../cxx_impl/src/foundation/event_emitter.h"
#include "../../../../../cxx_impl/src/foundation/geometry.h"
#include "../../../../../cxx_impl/src/foundation/id_allocator.h"
#include "../../../../../cxx_impl/src/foundation/native_object_provider.h"
#include "../../../../../cxx_impl/src/global_registry.h"
#include "../../../../../cxx_impl/src/image.h"
#include "../../../../../cxx_impl/src/keyboard_event.h"
#include "../../../../../cxx_impl/src/keyboard_monitor.h"
#include "../../../../../cxx_impl/src/menu.h"
#include "../../../../../cxx_impl/src/menu_event.h"
#include "../../../../../cxx_impl/src/message_dialog.h"
#include "../../../../../cxx_impl/src/placement.h"
#include "../../../../../cxx_impl/src/positioning_strategy.h"
#include "../../../../../cxx_impl/src/preferences.h"
#include "../../../../../cxx_impl/src/secure_storage.h"
#include "../../../../../cxx_impl/src/storage.h"
#include "../../../../../cxx_impl/src/tray_icon.h"
#include "../../../../../cxx_impl/src/tray_icon_event.h"
#include "../../../../../cxx_impl/src/tray_manager.h"
#include "../../../../../cxx_impl/src/window.h"
#include "../../../../../cxx_impl/src/window_event.h"
#include "../../../../../cxx_impl/src/window_manager.h"
#endif

// C API headers (available for both C and C++)
#include "../../../../../cxx_impl/src/capi/accessibility_manager_c.h"
#include "../../../../../cxx_impl/src/capi/application_c.h"
#include "../../../../../cxx_impl/src/capi/display_c.h"
#include "../../../../../cxx_impl/src/capi/display_manager_c.h"
#include "../../../../../cxx_impl/src/capi/geometry_c.h"
#include "../../../../../cxx_impl/src/capi/image_c.h"
#include "../../../../../cxx_impl/src/capi/keyboard_monitor_c.h"
#include "../../../../../cxx_impl/src/capi/menu_c.h"
#include "../../../../../cxx_impl/src/capi/message_dialog_c.h"
#include "../../../../../cxx_impl/src/capi/positioning_strategy_c.h"
#include "../../../../../cxx_impl/src/capi/preferences_c.h"
#include "../../../../../cxx_impl/src/capi/secure_storage_c.h"
#include "../../../../../cxx_impl/src/capi/string_utils_c.h"
#include "../../../../../cxx_impl/src/capi/tray_icon_c.h"
#include "../../../../../cxx_impl/src/capi/tray_manager_c.h"
#include "../../../../../cxx_impl/src/capi/window_c.h"
#include "../../../../../cxx_impl/src/capi/window_manager_c.h"
